@echo off
echo Starting Android Emulator...
start "Android Emulator" "C:\Users\ikizler1\AppData\Local\Android\Sdk\emulator\emulator.exe" -avd Medium_Phone_API_36

echo Waiting for emulator to boot...
timeout /t 30 /nobreak >nul

echo Building and installing app...
gradlew.bat assembleDebug
if %errorlevel% equ 0 (
    echo Installing to emulator...
    "C:\Users\ikizler1\AppData\Local\Android\Sdk\platform-tools\adb.exe" -s emulator-5554 install -r "app\build\outputs\apk\debug\app-debug.apk"
    echo Starting app...
    "C:\Users\ikizler1\AppData\Local\Android\Sdk\platform-tools\adb.exe" -s emulator-5554 shell am start -n com.example.ranking/.MainActivity
    echo Done! App is running in emulator.
) else (
    echo Build failed. Using existing APK...
    "C:\Users\ikizler1\AppData\Local\Android\Sdk\platform-tools\adb.exe" -s emulator-5554 install -r "app\build\outputs\apk\debug\app-debug.apk"
    echo Starting app...
    "C:\Users\ikizler1\AppData\Local\Android\Sdk\platform-tools\adb.exe" -s emulator-5554 shell am start -n com.example.ranking/.MainActivity
)
pause